version: '3.8'

services:
  dev:
    container_name: aluraflix_dev
    image: docker.io/library/aluraflix:alpine-latest
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    volumes:
      - .:/opt/aluraflix
      - /opt/aluraflix/node_modules
  db:
    image: postgres:alpine
    container_name: aluraflix_pgsql
    env_file:
      - .env
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /opt/aluraflix/docker-volumes/db/:/var/lib/postgresql/data
  redis:
    container_name: aluraflix-redis
    image: redis:alpine
    command: --bind 0.0.0.0
    ports:
      - '6379:6379'
    restart: always
