version: '3.8'

services:
  db:
    container_name: aluraflix
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin4_aluraflix
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
