version: '3.8'

services:
  dev:
    container_name: aluraflix_dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    environment:
      DB_HOST: host.docker.internal
    networks:
      - public
      - private
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  prod:
    container_name: aluraflix_prod
    image: docker.io/library/aluraflix:latest
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:prod
    env_file:
      - .env
    environment:
      DB_HOST: host.docker.internal
    networks:
      - public
      - private
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:alpine
    container_name: aluraflix_pgsql
    env_file:
      - .env
    restart: always
    networks:
      - private
    ports:
      - '5432:5432'
    volumes:
      - /usr/src/app/aluraflix/docker-volumes/db/:/var/lib/postgresql/data
  redis:
    container_name: aluraflix-redis
    image: redis:alpine
    networks:
      - private
    command: --bind 0.0.0.0
    ports:
      - '6379:6379'
    restart: always
networks:
  public:
  private:
