version: '3.8'

services:
  dev:
    container_name: aluraflix_dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  prod:
    container_name: aluraflix_prod
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:prod
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    container_name: aluraflix_pgsql
    image: postgres:alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - /usr/src/app/aluraflix/docker-volumes/db/:/var/lib/postgresql/data
  redis:
    container_name: aluraflix-redis
    image: redis:alpine
    command: --bind 0.0.0.0
    ports:
      - '6379:6379'
    restart: always
